src/Entity/AddressBook.php
<?php


namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\AddressBookRepository;

/**
 * @ORM\Entity
 * @ORM\Table(name="ADDRESS_BOOK")
 * @ORM\Entity(repositoryClass=AddressBookRepository::class)
 */
class AddressBook
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $Id;

    /**
     * @var string
     * @ORM\Column(name="FIRST_NAME", type="string", length=512, nullable=false)
     */
    private $first_name;

    /**
     * @var string
     * @ORM\Column(name="LAST_NAME", type="string", length=512, nullable=false)
     */
    private $last_name;

    /**
     * @var string
     * @ORM\Column(name="STREET_ADDRESS", type="string", length=512, nullable=false)
     */
    private $street_address;

    /**
     * @var string
     * @ORM\Column(name="ZIP_CODE", type="string", length=512, nullable=false)
     */
    private $zip_code;

    /**
     * @var string
     * @ORM\Column(name="CITY", type="string", length=512, nullable=false)
     */
    private $city;

    /**
     * @var string
     * @ORM\Column(name="COUNTRY", type="string", length=512, nullable=false)
     */
    private $country;

    /**
     * @var integer
     * @ORM\Column(name="PHONE_NUMBER", type="integer", length=512, nullable=false)
     */
    private $phone_number;

    /**
     * @var \DateTime
     * @ORM\Column(name="BIRTH_DATE", type="date", nullable=false)
     */
    private $birth_date;

    /**
     * @var string
     * @ORM\Column(name="EMAIL_ADDRESS", type="string",length=125, nullable=false)
     */
    private $email_address;

    /**
     * @var string
     * @ORM\Column(name="PICTURE", type="string",length=125, nullable=false)
     */
    private $picture;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * @param int $Id
     */
    public function setId($Id)
    {
        $this->Id = $Id;
    }

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * @param string $first_name
     */
    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * @param string $last_name
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;
    }

    /**
     * @return string
     */
    public function getStreetAddress()
    {
        return $this->street_address;
    }

    /**
     * @param string $street_address
     */
    public function setStreetAddress($street_address)
    {
        $this->street_address = $street_address;
    }

    /**
     * @return string
     */
    public function getZipCode()
    {
        return $this->zip_code;
    }

    /**
     * @param string $zip_code
     */
    public function setZipCode($zip_code)
    {
        $this->zip_code = $zip_code;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param string $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * @return int
     */
    public function getPhoneNumber()
    {
        return $this->phone_number;
    }

    /**
     * @param int $phone_number
     */
    public function setPhoneNumber($phone_number)
    {
        $this->phone_number = $phone_number;
    }

    /**
     * @return \DateTime
     */
    public function getBirthDate()
    {
        return $this->birth_date;
    }

    /**
     * @param \DateTime $birth_date
     */
    public function setBirthDate($birth_date)
    {
        $this->birth_date = $birth_date;
    }

    /**
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->email_address;
    }

    /**
     * @param string $email_address
     */
    public function setEmailAddress($email_address)
    {
        $this->email_address = $email_address;
    }

    /**
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * @param string $picture
     */
    public function setPicture($picture)
    {
        $this->picture = $picture;
    }

}

src/Form/AddressBookType.php
<?php


namespace App\Form;

use App\Entity\AddressBook;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class AddressBookType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('FirstName', TextType::class, ['label' => 'First Name','attr'=>['class'=>'from-control']]);
        $builder->add('LastName', TextType::class, ['label' => 'Last Name','attr'=>['class'=>'from-control']]);
        $builder->add('StreetAddress', TextType::class, ['label' => 'Street Address','attr'=>['class'=>'from-control']]);
        $builder->add('ZipCode', TextType::class, ['label' => 'Zip Code','attr'=>['class'=>'from-control']]);
        $builder->add('City', TextType::class, ['label' => 'City','attr'=>['class'=>'from-control']]);
        $builder->add('Country', CountryType::class, ['label' => 'Country','attr'=>['class'=>'from-control']]);
        $builder->add('PhoneNumber', TelType::class, ['label' => 'Phone Number','attr'=>['class'=>'from-control']]);
        $builder->add('BirthDate', DateType::class, ['label' => 'Birth Date', 'invalid_message' => "You've Entered an Invalid Date",'attr'=>['class'=>'from-control']]);
        $builder->add('EmailAddress', EmailType::class, ['label' => 'Email Address','attr'=>['class'=>'from-control']]);
        $data = $builder->getData();
        if ($data->getPicture() != null){
            $builder->add('PictureFile', FileType::class, ['required'=>false,'mapped'=>false,'label' => 'Picture','attr'=>['class'=>'from-control'],'data_class'=>null]);
        }
        else {
            $builder->add('PictureFile', FileType::class, ['constraints'=>[new NotBlank(["message"=>"Picture Is Required"])],'required'=>false,'mapped'=>false,'label' => 'Picture','attr'=>['class'=>'from-control'],'data_class'=>null]);
        }
        $builder->add('Submit', SubmitType::class, ['label' => 'Submit','attr'=>['formnovalidate'=>true,'class'=>'btn btn-primary float-right']]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AddressBook::class,
        ]);
    }

}

src/Controller/AddressBookController.php
<?php


namespace App\Controller;


use App\Entity\AddressBook;
use App\Form\AddressBookType;
use App\Services\FileUploader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class AddressBookController extends AbstractController
{
    /**
     * @Route("/",name="home")
    */
    public function homeIndex(){
        $em = $this->getDoctrine()->getManager();
        $address_book_repo = $em->getRepository(AddressBook::class);
        $address_books = $address_book_repo->getAll();
        return $this->render("AddressBook/index.html.twig",["address_books"=>$address_books]);
    }

    /**
     * @Route("/add",name="add")
     * @param Request $request
     * @param ValidatorInterface $validator
     * @param FileUploader $file_uploader
     * @return RedirectResponse|Response
     */
    public function addIndex(Request $request,ValidatorInterface $validator,FileUploader $file_uploader){
        $address_book = new AddressBook();
        $form = $this->createForm(AddressBookType::class,$address_book);
        $form->handleRequest($request);
        $errors = [];
        if ($form->isSubmitted()){
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                /** @var UploadedFile $file */
                $file = $request->files->get("address_book")["PictureFile"];
                $file_name = $file_uploader->upload($file);
                $address_book->setPicture($file_name);
                $em->persist($address_book);
                $em->flush();
                return $this->redirect($this->generateUrl("home"));
            }
            else {
                $errors = $validator->validate($form);
            }
        }
        return $this->render("AddressBook/form.html.twig",[
            'form' => $form->createView(),
            'picture_path' => "#",
            'errors' => $errors
        ]);
    }

    /**
     * @Route("/edit/{address_book}",name="edit")
     * @param Request $request
     * @param AddressBook $address_book
     * @param ValidatorInterface $validator
     * @param FileUploader $file_uploader
     * @return RedirectResponse|Response
     */
    public function editIndex(Request $request,AddressBook $address_book,ValidatorInterface $validator,FileUploader $file_uploader){
        $form = $this->createForm(AddressBookType::class,$address_book);
        $form->handleRequest($request);
        $errors = [];
        $picture_name = $address_book->getPicture();
        if ($form->isSubmitted()){
            /** @var UploadedFile $file */
            $file = $request->files->get("address_book")["PictureFile"];
            if ($file){
                $picture_name = $file->getClientOriginalName();
            }
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                /** @var UploadedFile $file */
                $file = $request->files->get("address_book")["PictureFile"];
                if ($file) {
                    $file_uploader->remove($address_book->getPicture());
                    $file_name = $file_uploader->upload($file);
                    $address_book->setPicture($file_name);
                }
                $em->persist($address_book);
                $em->flush();
                return $this->redirect($this->generateUrl("home"));
            }
            else {
                $errors = $validator->validate($form);
            }
        }
        return $this->render("AddressBook/form.html.twig",[
            'form' => $form->createView(),
            'picture_path' => "/uploads/".$address_book->getPicture(),
            'picture_name' => $picture_name,
            'errors' => $errors
        ]);
    }

    /**
     * @Route("/delete/{address_book}",name="delete")
     * @param Request $request
     * @param AddressBook $address_book
     * @param FileUploader $file_uploader
     * @return RedirectResponse|Response
     */
    public function deleteIndex(Request $request,AddressBook $address_book,FileUploader $file_uploader){
        $em = $this->getDoctrine()->getManager();
        $file_uploader->remove($address_book->getPicture());
        $em->remove($address_book);
        $em->flush();
        return $this->redirect($this->generateUrl("home"));
    }
}

templates/AddressBook/form.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="p-5 address-book-form">
        {{ form_start(form) }}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="{{ form.FirstName.vars.id }}">{{ form.FirstName.vars.label }}</label>
                    {{ form_widget(form.FirstName) }}
                </div>
                <div class="form-group col-md-6">
                    <label for="{{ form.LastName.vars.id }}">{{ form.LastName.vars.label }}</label>
                    {{ form_widget(form.LastName) }}
                </div>
            </div>
            <div class="form-group">
                <label for="{{ form.BirthDate.vars.id }}">{{ form.BirthDate.vars.label }}</label>
                {{ form_widget(form.BirthDate) }}
            </div>
            <div class="form-row">
                <div class="form-group col-md-5">
                    <label for="{{ form.Country.vars.id }}">{{ form.Country.vars.label }}</label>
                    {{ form_widget(form.Country) }}
                </div>
                <div class="form-group col-md-5">
                    <label for="{{ form.City.vars.id }}">{{ form.City.vars.label }}</label>
                    {{ form_widget(form.City) }}
                </div>
                <div class="form-group col-md-2">
                    <label for="{{ form.ZipCode.vars.id }}">{{ form.ZipCode.vars.label }}</label>
                    {{ form_widget(form.ZipCode) }}
                </div>
            </div>
            <div class="form-group">
            <label for="{{ form.StreetAddress.vars.id }}">{{ form.StreetAddress.vars.label }}</label>
            {{ form_widget(form.StreetAddress) }}
        </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="{{ form.EmailAddress.vars.id }}">{{ form.EmailAddress.vars.label }}</label>
                    {{ form_widget(form.EmailAddress) }}
                </div>
                <div class="form-group col-md-2">
                    <label for="{{ form.PhoneNumber.vars.id }}">{{ form.PhoneNumber.vars.label }}</label>
                    {{ form_widget(form.PhoneNumber) }}
                </div>
            </div>
        <div class="form-row">
            <div class="form-group col-md-10">
                <label for="{{ form.PictureFile.vars.id }}">
                    <span>{{ form.PictureFile.vars.label }} </span>
                    <a href="{{ picture_path }}" id="view_picture" class="d-inline-block fa fa-eye text-primary"> </a>
                </label>
                {{ form_widget(form.PictureFile) }}
            </div>
        </div>
            <div class="form-group">
                {{ form_widget(form.Submit) }}
            </div>
        {% if errors is defined and errors|length > 0 %}
            <span class="text-danger"> Please Fix The Following Issues !</span>
            <ul>
                {% for error in errors %}
                    <li>{{ error.message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        </div>
        {{ form_end(form) }}
    <script>
        const view_picture = document.getElementById("view_picture");
        const upload_picture = document.getElementById("{{ form.vars.name }}_PictureFile");
        const picture_path = "{{ picture_path }}";
        view_picture.onclick = e => {
            e.preventDefault();
            const path = upload_picture.files;
            if (path.length > 0) {
                const href = URL.createObjectURL(path[0]);
                window.open(href, '_blank');
            }
            else if (picture_path !== "#"){
                const redirectWindow = window.open(picture_path, '_blank');
                redirectWindow.location;
            }
            else {
                alert("No Picture !!");
            }
        };
        upload_picture.onchange = e => {
            var str = e.target.value;
            str = str.substring(str.lastIndexOf('\\') + 1);
            e.target.nextSibling.innerHTML = str;
        }
        {% if picture_name is defined and picture_name != null %}
            upload_picture.nextSibling.innerHTML = "{{ picture_name }}";
        {% endif %}
    </script>
{% endblock %}

templates/AddressBook/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <table class="table table-light table-light table-striped table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th scope="col" class="text-center">#</th>
            <th scope="col" class="text-center">Full Name</th>
            <th scope="col" class="text-center">Street Address</th>
            <th scope="col" class="text-center">City</th>
            <th scope="col" class="text-center">Phone Number</th>
            <th scope="col" class="text-center">Email Address</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for address_book in address_books %}
            <tr>
                <th class="text-center" scope="row">{{ loop.index }}</th>
                <td class="text-center">{{ address_book["first_name"] ~ "  " ~ address_book["last_name"] }}</td>
                <td class="text-center">{{ address_book["street_address"]}}</td>
                <td class="text-center">{{ address_book["city"]}}</td>
                <td class="text-center">{{ address_book["phone_number"]}}</td>
                <td class="text-center">{{ address_book["email_address"]}}</td>
                <td class="text-center">
                    <div class="d-flex justify-content-around">
                        <a class="text-primary" href="{{ path('edit',{address_book:address_book["Id"]}) }}">Update</a>
                        <a class="text-danger" href="{{ path('delete',{address_book:address_book["Id"]}) }}">Delete</a>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}